spring:
  application:
    name: config-default

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka     
  instance:
    prefer-ip-address: true 
